# Data-only resource file. Edit IMBUABLE_ITEMS_RESOURCE to adjust imbuable item slots.
IMBUABLE_ITEMS_RESOURCE = {
    "notes": [
        "Legs cannot be imbued.",
    ],
    "categories": [
        {
            "name": "Helmets",
            "items": [
                {"name": "Alicorn Headguard", "slots": 2, "category": "HELMET"},
                {"name": "Amazon Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Ancient Tiara", "slots": 2, "category": "HELMET"},
                {"name": "Antler-Horn Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Arboreal Crown", "slots": 2, "category": "HELMET"},
                {"name": "Arcanomancer Regalia", "slots": 2, "category": "HELMET"},
                {"name": "Batwing Hat", "slots": 1, "category": "HELMET"},
                {"name": "Bonelord Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Cobra Hood", "slots": 2, "category": "HELMET"},
                {"name": "Coned Hat of Enlightenment", "slots": 1, "category": "HELMET"},
                {"name": "Crown Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Crusader Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Dark Vision Bandana", "slots": 2, "category": "HELMET"},
                {"name": "Dark Whispers", "slots": 2, "category": "HELMET"},
                {"name": "Demon Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Demon Mengu", "slots": 2, "category": "HELMET"},
                {"name": "Demonfang Mask", "slots": 2, "category": "HELMET"},
                {"name": "Dreadfire Headpiece", "slots": 2, "category": "HELMET"},
                {"name": "Dwarven Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Eldritch Cowl", "slots": 2, "category": "HELMET"},
                {"name": "Eldritch Hood", "slots": 2, "category": "HELMET"},
                {"name": "Elite Draken Helmet", "slots": 1, "category": "HELMET"},
                {"name": "Ethereal Coned Hat", "slots": 2, "category": "HELMET"},
                {"name": "Falcon Circlet", "slots": 2, "category": "HELMET"},
                {"name": "Falcon Coif", "slots": 2, "category": "HELMET"},
                {"name": "Fur Cap", "slots": 2, "category": "HELMET"},
                {"name": "Galea Mortis", "slots": 2, "category": "HELMET"},
                {"name": "Gnome Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Golden Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Green Demon Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Hat of the Mad", "slots": 1, "category": "HELMET"},
                {"name": "Hellstalker Visor", "slots": 2, "category": "HELMET"},
                {"name": "Helmet of Nature", "slots": 2, "category": "HELMET"},
                {"name": "Helmet of Ultimate Terror", "slots": 2, "category": "HELMET"},
                {"name": "Helmet of the Lost", "slots": 2, "category": "HELMET"},
                {"name": "Jade Conical Hat", "slots": 1, "category": "HELMET"},
                {"name": "Jade Hat", "slots": 1, "category": "HELMET"},
                {"name": "Lion Spangenhelm", "slots": 2, "category": "HELMET"},
                {"name": "Mage Hat", "slots": 2, "category": "HELMET"},
                {"name": "Magician Hat", "slots": 2, "category": "HELMET"},
                {"name": "Maliceforged Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Norcferatu Bonehood", "slots": 2, "category": "HELMET"},
                {"name": "Norcferatu Skullguard", "slots": 2, "category": "HELMET"},
                {"name": "Odd Hat", "slots": 2, "category": "HELMET"},
                {"name": "Royal Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Shamanic Mask", "slots": 2, "category": "HELMET"},
                {"name": "Skull Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Spiritthorn Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Stag Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Stoic Iks Casque", "slots": 2, "category": "HELMET"},
                {"name": "Stoic Iks Headpiece", "slots": 2, "category": "HELMET"},
                {"name": "Terra Helmet", "slots": 1, "category": "HELMET"},
                {"name": "Visage of the End Days", "slots": 2, "category": "HELMET"},
                {"name": "Warrior Helmet", "slots": 2, "category": "HELMET"},
                {"name": "Witch Hat", "slots": 1, "category": "HELMET"},
                {"name": "Yalahari Mask", "slots": 1, "category": "HELMET"},
                {"name": "Zaoan Helmet", "slots": 1, "category": "HELMET"},
            ],
        },
        {
            "name": "Armors",
            "items": [
                {"name": "Albino Plate", "slots": 2, "category": "ARMOR"},
                {"name": "Amazon Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Arcane Dragon Robe", "slots": 1, "category": "ARMOR"},
                {"name": "Bear Skin", "slots": 1, "category": "ARMOR"},
                {"name": "Blue Robe", "slots": 2, "category": "ARMOR"},
                {"name": "Chain Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Crown Armor", "slots": 1, "category": "ARMOR"},
                {"name": "Dauntless Dragon Scale Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Dawnfire Sherwani", "slots": 1, "category": "ARMOR"},
                {"name": "Death Oyoroi", "slots": 1, "category": "ARMOR"},
                {"name": "Demon Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Depth Lorica", "slots": 2, "category": "ARMOR"},
                {"name": "Dragon Scale Mail", "slots": 1, "category": "ARMOR"},
                {"name": "Dream Shroud", "slots": 1, "category": "ARMOR"},
                {"name": "Dwarven Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Eldritch Cuirass", "slots": 2, "category": "ARMOR"},
                {"name": "Elite Draken Mail", "slots": 2, "category": "ARMOR"},
                {"name": "Elven Mail", "slots": 3, "category": "ARMOR"},
                {"name": "Embrace of Nature", "slots": 1, "category": "ARMOR"},
                {"name": "Falcon Plate", "slots": 2, "category": "ARMOR"},
                {"name": "Ghost Chestplate", "slots": 2, "category": "ARMOR"},
                {"name": "Gnome Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Gnomish Cuirass", "slots": 1, "category": "ARMOR"},
                {"name": "Golden Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Green Demon Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Heat Core", "slots": 2, "category": "ARMOR"},
                {"name": "Heavy Metal T-Shirt", "slots": 2, "category": "ARMOR"},
                {"name": "Knight Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Leopard Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Lion Plate", "slots": 2, "category": "ARMOR"},
                {"name": "Living Armor", "slots": 1, "category": "ARMOR"},
                {"name": "Magic Plate Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Mammoth Fur Cape", "slots": 2, "category": "ARMOR"},
                {"name": "Master Archer's Armor", "slots": 1, "category": "ARMOR"},
                {"name": "Merudri Battle Mail", "slots": 2, "category": "ARMOR"},
                {"name": "Merudri Nanbando", "slots": 1, "category": "ARMOR"},
                {"name": "Midnight Tunic", "slots": 1, "category": "ARMOR"},
                {"name": "Mooh'tah Plate", "slots": 2, "category": "ARMOR"},
                {"name": "Mutated Skin Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Mystical Dragon Robe", "slots": 1, "category": "ARMOR"},
                {"name": "Naga Tanko", "slots": 2, "category": "ARMOR"},
                {"name": "Noble Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Norcferatu Bloodhide", "slots": 1, "category": "ARMOR"},
                {"name": "Norcferatu Bonecloak", "slots": 1, "category": "ARMOR"},
                {"name": "Norcferatu Tuskplate", "slots": 2, "category": "ARMOR"},
                {"name": "Ornate Chestplate", "slots": 2, "category": "ARMOR"},
                {"name": "Paladin Armor", "slots": 1, "category": "ARMOR"},
                {"name": "Prismatic Armor", "slots": 1, "category": "ARMOR"},
                {"name": "Robe of Enlightenment", "slots": 1, "category": "ARMOR"},
                {"name": "Soulgarb", "slots": 2, "category": "ARMOR"},
                {"name": "Soulmantle", "slots": 2, "category": "ARMOR"},
                {"name": "Soulshell", "slots": 2, "category": "ARMOR"},
                {"name": "Soulshroud", "slots": 2, "category": "ARMOR"},
                {"name": "Spiritthorn Armor", "slots": 2, "category": "ARMOR"},
                {"name": "Stag Plate", "slots": 2, "category": "ARMOR"},
                {"name": "Stag Robe", "slots": 2, "category": "ARMOR"},
                {"name": "Stoic Iks Chestplate", "slots": 2, "category": "ARMOR"},
                {"name": "Stoic Iks Cuirass", "slots": 1, "category": "ARMOR"},
                {"name": "Stoic Iks Robe", "slots": 2, "category": "ARMOR"},
                {"name": "Toga Mortis", "slots": 1, "category": "ARMOR"},
                {"name": "Unerring Dragon Scale Armor", "slots": 2, "category": "ARMOR"},
            ],
        },
        {
            "name": "Boots",
            "items": [
                {"name": "Alchemist's Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Badger Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Boots of Enlightenment", "slots": 1, "category": "BOOTS"},
                {"name": "Boots of Haste", "slots": 1, "category": "BOOTS"},
                {"name": "Bunnyslippers", "slots": 1, "category": "BOOTS"},
                {"name": "Cobra Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Coconut Shoes", "slots": 1, "category": "BOOTS"},
                {"name": "Crocodile Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Crystal Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Depth Calcei", "slots": 1, "category": "BOOTS"},
                {"name": "Dragon Scale Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Draken Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Eldritch Monk Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Feverbloom Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Frostflower Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Fur Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Glacier Shoes", "slots": 1, "category": "BOOTS"},
                {"name": "Gnomish Footwraps", "slots": 1, "category": "BOOTS"},
                {"name": "Golden Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Green Demon Slippers", "slots": 1, "category": "BOOTS"},
                {"name": "Guardian Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Iks Footwraps", "slots": 1, "category": "BOOTS"},
                {"name": "Leather Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Lightning Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Magma Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Make-Do Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Makeshift Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Metal Spats", "slots": 1, "category": "BOOTS"},
                {"name": "Mutant Bone Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Norcferatu Goretrampers", "slots": 1, "category": "BOOTS"},
                {"name": "Oriental Shoes", "slots": 1, "category": "BOOTS"},
                {"name": "Pair of Dreamwalkers", "slots": 1, "category": "BOOTS"},
                {"name": "Pair of Nightmare Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Pair of Soulstalkers", "slots": 1, "category": "BOOTS"},
                {"name": "Pair of Soulwalkers", "slots": 1, "category": "BOOTS"},
                {"name": "Patched Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Pirate Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Prismatic Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Sandals", "slots": 1, "category": "BOOTS"},
                {"name": "Sanguine Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Sanguine Galoshes", "slots": 1, "category": "BOOTS"},
                {"name": "Soulsoles", "slots": 1, "category": "BOOTS"},
                {"name": "Stag Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Stag Footwraps", "slots": 1, "category": "BOOTS"},
                {"name": "Stag Shinguards", "slots": 1, "category": "BOOTS"},
                {"name": "Steel Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Stoic Iks Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Stoic Iks Sandals", "slots": 1, "category": "BOOTS"},
                {"name": "Terra Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Treader of Torment", "slots": 1, "category": "BOOTS"},
                {"name": "Vampire Silk Slippers", "slots": 1, "category": "BOOTS"},
                {"name": "Winged Boots", "slots": 1, "category": "BOOTS"},
                {"name": "Yalahari Footwraps", "slots": 1, "category": "BOOTS"},
                {"name": "Zaoan Shoes", "slots": 1, "category": "BOOTS"},
            ],
        },
        {
            "name": "Shields",
            "items": [
                {"name": "Amazon Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Biscuit Barrier", "slots": 1, "category": "SHIELD"},
                {"name": "Bonelord Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Carapace Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Castle Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Crown Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Death Gaze", "slots": 1, "category": "SHIELD"},
                {"name": "Demon Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Depth Scutum", "slots": 1, "category": "SHIELD"},
                {"name": "Dragon Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Ectoplasmic Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Eldritch Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Falcon Escutcheon", "slots": 1, "category": "SHIELD"},
                {"name": "Falcon Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Gnome Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Great Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Griffin Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Haunted Mirror Piece", "slots": 1, "category": "SHIELD"},
                {"name": "Lion Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Mastermind Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Meat Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Medusa Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Necromancer Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Nightmare Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Norse Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Ornamented Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Ornate Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Phoenix Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Refined Stag Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Rift Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Runic Ice Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Sentinel Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Shield of Care", "slots": 1, "category": "SHIELD"},
                {"name": "Shield of Corruption", "slots": 1, "category": "SHIELD"},
                {"name": "Shield of the White Knight", "slots": 1, "category": "SHIELD"},
                {"name": "Soulbastion", "slots": 1, "category": "SHIELD"},
                {"name": "Stag Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Steel Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Tempest Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Tower Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Vampire Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Viking Shield", "slots": 1, "category": "SHIELD"},
                {"name": "Warrior's Shield", "slots": 1, "category": "SHIELD"},
            ],
        },
        {
            "name": "Spellbooks",
            "items": [
                {"name": "Alchemist's Notepad", "slots": 1, "category": "SHIELD"},
                {"name": "Arboreal Tome", "slots": 1, "category": "SHIELD"},
                {"name": "Arcanomancer Folio", "slots": 1, "category": "SHIELD"},
                {"name": "Book of Lies", "slots": 1, "category": "SHIELD"},
                {"name": "Brain in a Jar", "slots": 1, "category": "SHIELD"},
                {"name": "Cocoa Grimoire", "slots": 1, "category": "SHIELD"},
                {"name": "Creamy Grimoire", "slots": 1, "category": "SHIELD"},
                {"name": "Eldritch Folio", "slots": 1, "category": "SHIELD"},
                {"name": "Eldritch Tome", "slots": 1, "category": "SHIELD"},
                {"name": "Lion Spellbook", "slots": 1, "category": "SHIELD"},
                {"name": "Shoulder Plate", "slots": 1, "category": "SHIELD"},
                {"name": "Spellbook of Enlightenment", "slots": 1, "category": "SHIELD"},
                {"name": "Spellbook of Warding", "slots": 1, "category": "SHIELD"},
                {"name": "Spellbook", "slots": 1, "category": "SHIELD"},
                {"name": "Spirit Guide", "slots": 1, "category": "SHIELD"},
                {"name": "Stag Scrolls", "slots": 1, "category": "SHIELD"},
                {"name": "Stag Spellbook", "slots": 1, "category": "SHIELD"},
                {"name": "Umbral Master Spellbook", "slots": 1, "category": "SHIELD"},
                {"name": "Umbral Spellbook", "slots": 1, "category": "SHIELD"},
                {"name": "Wooden Spellbook", "slots": 1, "category": "SHIELD"},
            ],
        },
        {
            "name": "Rods",
            "items": [
                {"name": "Amber Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Cobra Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Jaw", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Deepling Ceremonial Dagger", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Deepling Fork", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Rod", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Dream Blossom Staff", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Eldritch Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Energized Limb", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Jungle Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Naga Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Northwind Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Ogre Scepta", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Rod", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Rod of Carving", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rod of Destruction", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rod of Mayhem", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rod of Remedy", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sanguine Rod", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Rod", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Soulhexer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Underworld Rod", "slots": 2, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Wands",
            "items": [
                {"name": "Amber Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Cobra Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Bile", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Deepling Ceremonial Dagger", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Deepling Fork", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Wand", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Dream Blossom Staff", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Eldritch Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Energized Limb", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Coil", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Jungle Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Naga Wand", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Wand", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Sanguine Coil", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Wand", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Soultainter", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Carving", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Destruction", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Draconia", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Dragonbreath", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Mayhem", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Remedy", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Starstorm", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wand of Voodoo", "slots": 2, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Bows",
            "items": [
                {"name": "Amber Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bow of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bow of Cataclysm", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bow of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bow of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bow of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Composite Hornbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crypt Spine", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Bow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Eldritch Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Elvish Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Falcon Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hive Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Icicle Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Inferniarch Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Jungle Bow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Longbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Living Vine Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Musician's Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Mycological Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Bow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rift Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Sanguine Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Silkweaver Bow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Bow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Soulbleeder", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Umbral Bow", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Bow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Warsinger Bow", "slots": 3, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Crossbows",
            "items": [
                {"name": "Amber Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Chain Bolter", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Cobra Crossbow", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crossbow of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crossbow of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crossbow of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crossbow of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Arbalest", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Inferniarch Arbalest", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Modified Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Naga Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Arbalest", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rift Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Royal Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Sanguine Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Arbalest", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Soulpiercer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "The Devileye", "slots": 3, "category": "WEAPON_1H"},
                {"name": "The Ironworker", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Thorn Spitter", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Triple Bolt Crossbow", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Umbral Crossbow", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Crossbow", "slots": 2, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Axe Weapons",
            "items": [
                {"name": "Amber Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Amber Greataxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Axe of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Axe of Destruction", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Axe of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Axe of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Barbarian Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Beastslayer Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Butcher's Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Chopper of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Chopper of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Chopper of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Chopper of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Cobra Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Splitter", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crystalline Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Demonwing Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Dragon Lance", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Battleaxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Greataxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Drakinata", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Dreaded Cleaver", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Dwarven Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Eldritch Greataxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Executioner", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Battleaxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Greataxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Battleaxe", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Hatchet", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Great Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Guardian Halberd", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Headchopper", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hellforged Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Heroic Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Hive Scythe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Impaler", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Battleaxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Greataxe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Knight Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Mythril Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Naga Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Noble Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Phantasmal Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Ravager's Axe", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Battleaxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Greataxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Rift Lance", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Royal Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Ruthless Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sanguine Battleaxe", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Sanguine Hatchet", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Battleaxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Greataxe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Solar Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Soulbiter", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Souleater (Axe)", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Stonecutter Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Throwing Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Twin Axe", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Umbral Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Chopper", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Axe", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Chopper", "slots": 2, "category": "WEAPON_1H"},
                {"name": "War Axe", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Warrior's Axe", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Zaoan Halberd", "slots": 3, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Club Weapons",
            "items": [
                {"name": "Abyss Hammer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Amber Bludgeon", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Amber Cudgel", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Amber Staff", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Arcane Staff", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Blessed Sceptre", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Clerical Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Cobra Club", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Cranial Basher", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Breaker", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Crystal Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Deepling Squelcher", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Demonbone", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Dragonbone Staff", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Flail", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Warhammer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Eldritch Warmace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Energized Demonbone", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Warmace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Glooth Whip", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Bludgeon", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Cudgel", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Hammer of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hammer of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hammer of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hammer of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Hammer of Wrath", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Heavy Mace", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Inferniarch Flail", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Warhammer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Jungle Flail", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Life Preserver", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Hammer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lunar Staff", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Mace of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Mace of Destruction", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Mace of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Mace of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Maimer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Mortal Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Mycological Mace", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Naga Club", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Obsidian Truncheon", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Onyx Flail", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Orcish Maul", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Ornate Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Queen's Sceptre", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Flail", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Warhammer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Resizer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rotten Demonbone", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sanguine Bludgeon", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Sanguine Cudgel", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sapphire Hammer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Shadow Sceptre", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Silver Mace", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Flail", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Warhammer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Skull Staff", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Skullcrusher", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Snake God's Sceptre", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Soulcrusher", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Soulmaimer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Spiked Squelcher", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Sulphurous Demonbone", "slots": 2, "category": "WEAPON_1H"},
                {"name": "The Stomper", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Thunder Hammer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Umbral Hammer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Mace", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Hammer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Umbral Master Mace", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Unliving Demonbone", "slots": 2, "category": "WEAPON_1H"},
                {"name": "War Hammer", "slots": 3, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Sword Weapons",
            "items": [
                {"name": "Amber Sabre", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Amber Slayer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Assassin Dagger", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Berserker", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Blacksteel Sword", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Blade of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Blade of Corruption", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Blade of Destruction", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Blade of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Blade of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Bloody Edge", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Bright Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Broadsword", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Cobra Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crimson Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Slicer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Demonrage Sword", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Djinn Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Dragon Slayer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Blade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Slayer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Eldritch Claymore", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Emerald Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Epee", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Longsword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Giant Sword", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Claymore", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Gnome Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Razor", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Haunted Blade", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Havoc Blade", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Inferniarch Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Inferniarch Slayer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Ink Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Longsword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Magic Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Mystic Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Naga Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Nightmare Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Relic Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Blade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Slayer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Runed Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sanguine Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sanguine Razor", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Shiny Blade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Blade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Slayer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Slayer of Carving", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Slayer of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Slayer of Mayhem", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Slayer of Remedy", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Soulcutter", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Soulshredder", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Spike Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Summerblade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Sword", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Tagralt Blade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Thaian Sword", "slots": 3, "category": "WEAPON_1H"},
                {"name": "The Avenger", "slots": 2, "category": "WEAPON_1H"},
                {"name": "The Epiphany", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Twiceslicer", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Twin Hooks", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Umbral Blade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Slayer", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Umbral Masterblade", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Slayer", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Winterblade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Wyvern Fang", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Zaoan Sword", "slots": 2, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Fist Fighting Weapons",
            "items": [
                {"name": "Amber Kusarigama", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Bambus Jo", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Cobra Bo", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Crypt Strike", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Depth Claws", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Drachaku", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Draining Inferniarch Claws", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Eldritch Crescent Moon Spade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Falcon Sai", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Fists of Enlightenment", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Gilded Eldritch Crescent Moon Spade", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Grand Sanguine Claws", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Inferniarch Claws", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Lion Claws", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Naga Katar", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Nunchaku of Destruction", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Nunchaku of Enlightenment", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Pair of Iron Fists", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Rending Inferniarch Claws", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Sai of Enlightenment", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Sai", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Sanguine Claws", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Siphoning Inferniarch Claws", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Soulkamas", "slots": 3, "category": "WEAPON_1H"},
                {"name": "Traditional Sai", "slots": 2, "category": "WEAPON_1H"},
                {"name": "Umbral Katar", "slots": 1, "category": "WEAPON_1H"},
                {"name": "Umbral Master Katar", "slots": 2, "category": "WEAPON_1H"},
            ],
        },
        {
            "name": "Backpacks",
            "items": [
                {"name": "25 Years Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Anniversary Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Backpack of Holding", "slots": 1, "category": "BACKPACK"},
                {"name": "Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Beach Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Birthday Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Blue Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Book Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Brocade Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Buggy Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Bursa Obscura", "slots": 1, "category": "BACKPACK"},
                {"name": "Cake Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Camouflage Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Changing Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Crown Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Crystal Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Deepling Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Demon Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Dragon Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Energetic Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Expedition Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Feedbag", "slots": 1, "category": "BACKPACK"},
                {"name": "Festive Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Fur Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Ghost Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Glooth Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Golden Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Green Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Grey Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Heart Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Jewelled Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Lilypad Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Minotaur Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Moon Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Mushroom Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Old and Used Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Orange Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Pannier Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Peppermint Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Pillow Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Pirate Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Purple Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Raccoon Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Red Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Santa Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Winged Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Wolf Backpack", "slots": 1, "category": "BACKPACK"},
                {"name": "Yellow Backpack", "slots": 1, "category": "BACKPACK"},
            ],
        },
    ],
}
